Feature dockerize snapshot script
cloudposse/kube-ebs-snapshot pull request #1
Opened 2017-04-18 08:21 UTC by goruha

## What
* Created script that make ebs snapshots based on pod volumes

## Why
* EBS snapshots is good way to create backups

2017-04-20 15:12 UTC, osterman commented on rootfs/bin/create-snapshot
> +
should `set -o pipefail` https://bclary.com/blog/2006/07/20/pipefail-testing-pipeline-exit-codes/

2017-04-20 15:14 UTC, osterman commented on rootfs/bin/create-snapshot
> +export DESCRIPTION=${DESCRIPTION:-"This is snapshot create automaticaly by kube-ebs-snapshot"}
`This snapshot was created automaticaly by kube-ebs-snapshot`

2017-04-20 15:16 UTC, osterman commented on rootfs/bin/create-snapshot
> +echo "Creating snapshots based on PVC"
`echo "Creating snapshots based on $NAME PVC in the $NAMESPACE namespace"`

2017-04-20 15:18 UTC, osterman commented on Dockerfile
> +          bash-completion && \
Can drop the support for `bash-completion`

2017-04-20 15:18 UTC, osterman commented on Dockerfile
> +    && ln -s /usr/local/aws/bin/aws_bash_completer /etc/bash_completion.d/aws.sh \
and drop this

2017-04-20 15:19 UTC, osterman commented on Makefile
> +SHELL = /bin/bash
Use the short notation? https://github.com/cloudposse/build-harness#usage

2017-04-20 15:20 UTC, osterman requested changes
See inline comments

2017-04-21 10:54 UTC, goruha commented on Dockerfile
> +          bash-completion && \
Done

2017-04-21 10:54 UTC, goruha commented on Dockerfile
> +    && ln -s /usr/local/aws/bin/aws_bash_completer /etc/bash_completion.d/aws.sh \
Done

2017-04-21 10:55 UTC, goruha commented on Makefile
> +SHELL = /bin/bash
Done

2017-04-21 10:56 UTC, goruha commented on rootfs/bin/create-snapshot
> +
Done

2017-04-21 10:57 UTC, goruha commented on rootfs/bin/create-snapshot
> +export DESCRIPTION=${DESCRIPTION:-"This is snapshot create automaticaly by kube-ebs-snapshot"}
Done

2017-04-21 10:57 UTC, goruha commented on rootfs/bin/create-snapshot
> +echo "Creating snapshots based on PVC"
Done

2017-05-30 23:57 UTC, osterman approved these changes

2017-05-30 23:58 UTC, merged